<div class="line-height-1-4em">
	<div class="font-14px font-type1"><center><b>PERJANJIAN PENITIPAN KENDARAAN BERMOTOR UNTUK LELANG</b></center></div><br />

	<div class="font-12px font-type1">Syarat dan ketentuan berikut berlaku untuk perjanjian jasa lelang, perjanjian penjualan multi saluran dengan mekanisme lelang antara Anda dan IBID - PT. Balai Lelang Serasi dan merupakan tambahan terhadap syarat dan ketentuan yang tercantum dalam Perjanjian Lelang.</div>

	<div class="font-12px font-type1">
		<ol>
			<li><p></p><p></p><p></p><p>Pihak Penandatangan, Pemberitahuan, Hukum yang Berlaku.</p><p>Kecuali disebutkan lain dalam Perjanjian Lelang, entitas kontrak IBID yang berlaku, alamat pemberitahuan, peraturan hukum atau tempat kerja, dan harus seperti yang tercantum pada halaman ini. Setiap tindakan hukum yang diajukan oleh Penjual dan Pembeli terkait dengan Perjanjian secara eksklusif di peradilan kontrak IBID yang berlaku sebagaimana mestinya. Setiap tindakan hukum yang dibawa oleh IBID terkait dengan Perjanjian ini harus diajukan secara khusus dalam jurisdiksi entitas kontrak IBID yang berlaku atas pertimbangan sendiri. Jika halaman ini menetapkan lebih dari satu jurisdiksi yang berlaku untuk Perjanjian Lelang, IBID dapat memilih jurisdiksi mana yang berlaku untuk tindakan hukum yang dibawa oleh IBID. Jika memungkinkan, para pihak secara tak dapat ditarik kembali melepaskan hak untuk menuntut pengadilan juri dalam perselisihan yang timbul atau terkait dengan Perjanjian ini.</p><p></p><p></p></li>
			
			<li><p></p><p></p><p>Layanan IBID.</p><p>Menurut ketentuan dalam Perjanjian ini, IBID&nbsp; menawarkan penggunaan website lelang yang berlaku, yang berfungsi sebagai platform yang dapat Anda gunakan untuk menitipkan kendaraan lelang maupun untuk mengikuti proses lelang. IBID merupakan pihak mengikat untuk menjual atau membeli kendaraan antara Penitip dan Peserta Lelang. IBID juga mewakili salah satu pihak dalam transaksi yang dihasilkan dari penggunaan website lelang.</p><p></p></li>
			
			<li><p><p>Format Pencantuman.</p><p>Ada dua format daftar kendaraan lelang yang tersedia di website :</p><p>(i) Lelang Live Auction : Layanan dimana Anda dapat menitipkan kendaraan untuk dilelang kepada IBID dan peserta yang ingin memenangkan unit harus mengikuti lelang secara terbuka dengan melakukan biddingbaik di lokasi lelang maupun diluar lokasi lelang menggunakan gadget peserta. Hanya penawar tertinggi yang memenuhi atau melampaui harga dasar yang dinyatakan sebagai pemenang.</p><p>(ii) Lelang Online Auction : Layanan dimana Anda dapat menitipkan kendaraan untuk dilelang kepada IBID dan penawar tertinggi yang memenuhi atau melampaui harga dasar hanya dengan menggunakan saluran online yang dinyatakan sebagai pemenang. IBID akan menetapkan dan menjadwalkan masa penawarannya.</p><p>IBID harus menggunakan usaha terbaiknya untuk memastikan bahwa teknologi dan sistem tersebut tersedia pada semua metode pelelangan yang disediakan :&nbsp;</p><p>(a) hanya lot yang dianggap layak oleh IBID yang ditawarkan dengan menggunakan teknologi dan sistem, dan&nbsp;</p><p>(b) keadaan tertentu mengenai internet dan teknologi yang digunakan berada di luar kendali IBID, dan sistem semacam itu mungkin tidak tersedia pada waktu tertentu.&nbsp;</p><p>Anda setuju bahwa IBID tidak dinyatakan sebagai pihak yang bertanggung jawab atas setiap dan semua klaim, tuntutan, gugatan, proses hukum, sebab-sebab proses hukum, ganti rugi, atau biaya yang timbul dari :</p><p>1. kegagalan internet, server atau komponen komputer dan komunikasi lainnya dan sistem , terlepas dari apakah kegagalan tersebut disebabkan oleh kelalaian IBID,</p><p>2. keputusan IBID untuk menggunakan teknologi atau sistem tersebut, atau</p><p>3. kegagalannya untuk menawarkan sistem tersebut setiap saat</p><br></p></li>
			
			<li><p></p><p></p><p></p><p></p><p>Inspeksi</p><p>Anda mengijinkan IBID atau perwakilannya yang berwenang untuk menguji dan memeriksa setiap kendaraan yang akan dititipkan. IBID harus membuat laporan inspeksi untuk setiap bagian Kendaraan yang diperiksa oleh IBID. Laporan Inspeksi adalah satu-satunya dan eksklusif milik IBID. Inspeksi IBID bertujuan melaporkan kondisi sistem kendaraan dan perlengkapan utama kendaraan, mendeteksi cacat atau kondisi tersembunyi atau penggunaan kendaraan atau teknik diagnostik secara fisik. Apabila kendaraan berada di lokasi Anda, maka kegagalan Anda untuk merawat kendaraan dengan benar sejak tanggal pemeriksaan / open house sampai pengambilan oleh pemenang dari lokasi Anda oleh Pemenang akan membatalkan pembelian.&nbsp;</p><p>Jika kendaraan tidak diperiksa, Anda harus menyediakan detail cantuman yang diperbarui ke IBID. Jika terjadi pelanggaran ketentuan yang ditentukan oleh IBID atas pertimbangannya yang wajar dan kendaraan telah terjual melalui website lelang, transaksi tersebut akan dibatalkan dan Anda akan dikenakan biaya administrasi selain penggantian biaya transportasi dan biaya lainnya yang dikeluarkan Pembeli.</p><p></p><p></p><p></p></li>
			
			<li><p></p><p></p><p></p><p></p><p></p><p>Pernyataan dan Jaminan Penitip.</p><p>Penitip menyatakan dan menjamin bahwa:&nbsp;</p><p>(a) Kendaraan yang akan dilelang bebas dan bersih dari setiap dan semua hak istimewa yang terdaftar dan tidak terdaftar, kecuali sudah dijelaskan kepada IBID sebelumnya,&nbsp;</p><p>(b) Kendaraan dalam kondisi operasi yang baik, bebas dari kerusakan material, kecuali sudah dijelaskan kepada IBID sebelumnya,&nbsp;</p><p>(c) Keterangan Kendaraan harus dijelaskan secara akurat, dan kendaraan tersebut tidak pernah diambil kembali, atau diklasifikasi kecuali sudah dijelaskan kepada IBID sebelumnya,</p><p>(d) Semua spedometer pada kendaraan mencerminkan jarak tempuh atau penggunaan sebenarnya kecuali sudah dijelaskan kepada IBID sebelumnya,</p><p>(e) Kendaraan belum dimodifikasi atau dirusak dengan cara apa pun yang bertentangan dengan undang-undang yang berlaku atau menyesatkan pembeli potensial, merusak perangkat kontrol emisi kecuali sudah dijelaskan kepada IBID sebelumnya,</p><p>(f) Kendaraan tidak diperoleh dengan dicuri atau dipalsukan, dan&nbsp;</p><p>(g) Penitip memberikan wewenang dengan menandatangani Perjanjian ini dan untuk melengkapi dan menyampaikan semua informasi yang dikirimkan ke IBID.</p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p>Batasan Penggunaan</p><p>Pembatasan penggunaan kendaraan. Dari saat Anda memberikan rincian pencantuman ke IBID atau inspeksi dilakukan oleh IBID sampai kendaraan dikeluarkan dari lokasinya oleh atau atas nama Pembeli setelah peserta dinyatakan sebagai pemenang, Anda tidak mengoperasikan, menyewakan, memodifikasi atau mengganti kendaraan selain hak dan pemulihan lain yang mungkin dimiliki oleh IBID. Jika Anda mengubah atau melakukan perbaikan atau perawatan lainnya pada kendaraan setelah pemeriksaan, pemeriksaan lain akan diperlukan, dan Anda akan dikenai biaya re-inspeksi dan biaya lain yang menyertainya.</p><p>IBID berhak menentukan jumlah pasti biaya re-Inspeksi dan biaya lain yang menyertainya untuk kendaraan yang memerlukan pemeriksaan ulang atas kebijakannya sendiri berdasarkan kasus per kasus.</p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Penggunaan kendaraan.</p><p>Anda memberi kuasa kepada IBID untuk mengoperasikan kendaraan dengan tujuan untuk mendemonstrasikannya ketika acara lelang berlangsung.</p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Larangan Pra-penjualan.</p><p>Baik IBID maupun Anda tidak akan menjual atau menawarkan kendaraan yang dititipkan untuk dijual secara utuh maupun per bagian kendaraan sebelum lelang langsung tanpa ijin tertulis dari IBID dan pihak terkait lainnya.</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Pelaksanaan Kewajiban Tertentu.</p><p>Selain upaya hukum lain yang mungkin ada, penitip tidak mengirimkan list yang akan dilelang atau menarik kendaraan dari acara lelang berlangsung, dengan ini penitip mengetahui dan menyetujui bahwa :</p><p>(a) Kerugian pada reputasi bisnis, merek dan pelanggan IBID signifikan dan tidak dapat diperbaiki, dan&nbsp;</p><p>(b) IBID dapat meminta penegakan Perjanjian ini dengan cara pelaksanaan kewajiban tertentu atau perintah pengadilan, tanpa persyaratan untuk mengirimkan jaminan atau jaminan lainnya.</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Risiko Rugi.</p><p>Penitip bertanggung jawab atas kehilangan atau kerusakan kendaraan, selain kehilangan atau kerusakan yang diakibatkan oleh kelalaian IBID, sampai yang paling awal:&nbsp;</p><p>(a) Jika kendaraan dijual melalui lelang,&nbsp;</p><p>(b) Penjual mengasuransikan / bertanggung jawab atas kendaraannya terhadap semua bahaya sehingga jika terjadi kerusakan atau penghancuran kendaraan atau bagiannya, semua hasil asuransi akan dikreditkan ke hasil penjualan kotor, terlepas dari tempat dimana kendaraan dilelang, dan pembayaran dilakukan ke IBID.</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Website dan jadwal lelang.</p><p>IBID sebagai agen Anda harus menawarkan kendaraan Anda untuk dilelang di lokasi lelang maupun secara online sesuai jadwal yang ditentukan dalam Perjanjian Penjualan. Kendaraan yang dititipkan akan segera diikutsertakan dalam jadwal lelang terdekat sesuai dengan informasi jadwal lelang yang tersedia pada website.</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Layanan tambahan</p><p>Anda dapat meminta salah satu layanan yang diuraikan sehubungan dengan pelelangan kendaraan (sebagai penitip maupun peserta lelang)</p><p>Anda setuju untuk membayar semua biaya karena layanan telah diterima (fee titip lelang). Biaya layanan akan dikurangkan dari jumlah harga yang terbentuk dari unit kendaraan yang terjual. Jika tidak terjual, maka biaya layanan akan ditagihkan langsung kepada Penjual.</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Pembayaran.</p><p>Pemenang lelang akan diberikan waktu selama 5 hari kerja untuk melakukan pelunasan setelah acara lelang berlangsung dengan transfer dana elektronik menggunakan Virtual Account yang telah disediakan. Jika dalam waktu 5 hari kerja pemenang tidak melunasi unit, maka pemenang dinyatakan wanprestasi, sehingga dana yang sudah didepositkan tidak dapat dikembalikan atau hangus.</p><p>Penitip lelang akan menerima pembayaran, jika unit terjual dalam lelang selama 7 hari kerja setelah acara lelang berlangsung dengan kalkulasi yang sudah disetujui sebelumnya dan dana diberikan via transfer langsung ke rekening penitip. Jika unit tidak dilunasi oleh pemenang maka penitip akan mendapatkan kompensasi sebesar 50% dari dana yang sudah didepositkan oleh pemenang.</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Biaya transaksi.</p><p>Anda menyetujui bahwa IBID dapat mengenakan biaya transaksi kepada pembeli berdasarkan harga jual masing-masing lot. (Biaya Administrasi)</p><p>Biaya Administrasi yang dikenakan ;</p><p>Pada saat pelunasan, pemenang dikenakan biaya administrasi per unit sebagai berikut:</p><p>a. Rp. 1.750,000,- (satu juta tujuh ratus lima puluh ribu rupiah)/NPL unit mobil</p><p>b. Rp. 250.000,- (dua ratus lima puluh ribu rupiah)/NPL unit motor</p><p>c. Rp. 5.000.000,- (lima juta rupiah)/NPL unit alat berat</p><p>d. Rp. 50.000,- (lima puluh ribu rupiah)/NPL unit Kamera</p><p>e. Rp. 100.000,- (seratus ribu rupiah)/NPL unit gadget&nbsp;</p><p>f. Rp. 150.000,- (seratus lima puluh ribu rupiah)/NPL Ipad atau Iphone&nbsp;</p><p>g. Rp. 300.000,- (tiga ratus ribu rupiah)/NPL Desktop+Monitor, Laptop</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Ganti Rugi</p><p>Apabila terjadi FORCE MAJOURE (keadaan kahar) seperti bencana alam, kerusuhan masa dan tindakan pemerintah dalam bidang moneter, maka segala akibat dan atau kerugian yang timbul menjadi tanggung jawab pemenang</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Pemberitahuan dan Pengendalian Klaim.</p><p>IBID&nbsp; harus segera memberi tahu Anda secara tertulis tentang gugatan atau tuntutan yang diancamkan atau yang sebenarnya dan cukup bekerja sama dengan Anda untuk memfasilitasi penyelesaian atau pembelaannya. Anda memiliki satu-satunya kendali atas pembelaan atau penyelesaian klaim atau permintaan apapun, dengan ketentuan bahwa IBID, atas pilihan dan biaya, dapat berpartisipasi dan tampil setara dengan Anda. Anda tidak boleh menyelesaikan tuntutan apapun tanpa persetujuan tertulis dari IBID.</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Buyback</p><p>IBID memberikan layanan untuk dilakukan buyback, apabila kendaraan yang telah dilakukan pembelian oleh peserta ternyata bermasalah seperti dengan keterangan blokir dokumen yang tidak dapat diselesaikan selama mendapat persetujuan dari penitip atau kendaraan batal terjual berdasarkan informasi dari penitip. Setiap klaim biaya tambahan diluar biaya pokok terjualnya kendaraan akan diajukan kepada penitip lelang dan biaya klaim yang diajukan akan dibayarkan selama mendapat persetujuan dari penitip.</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Sengketa Hukum.</p><p>Setiap klaim yang diajukan harus dalam persetujuan dan tidak bertentangan.</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Batasan.</p><p>Anda setuju bahwa pengajuan klaim yg timbul terkait dari perjanjian harus ada jangka waktunya dan bergantung pada persetujuan dari penitip. Lewat dari itu pihak IBID tidak akan bertanggung jawab.</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Pajak</p><p>IBID mengumpulkan dan membayarkan pajak penjualan kendaraan melalui metode lelang ke negara yang timbul atas penjualan kendaraan pada acara lelang berlangsung.</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Layanan IBID - PT. Balai Lelang Serasi</p><p>Pastikan Anda meninjau setiap bagian yang relevan dengan Perjanjian Anda. Kecuali ditentukan lain dalam Persyaratan ini, kata-kata yang dikapitalisasi memiliki arti yang tercantum dalam Perjanjian Penjualan.</p><p>Perjanjian ini berisi seluruh kesepakatan para pihak dan menggantikan semua komunikasi, perwakilan, pemahaman dan kesepakatan sebelumnya, baik lisan atau tertulis, antara kita. Jika terjadi pertentangan antara Persyaratan dan Perjanjian Penjualan ini, Perjanjian Penjualan harus dikendalikan. Jika ada ketentuan dalam Perjanjian ini dipegang oleh pengadilan yang berwenang tidak dapat dilaksanakan, maka ketentuan tersebut akan dikeluarkan dan ketentuan yang tersisa akan terus berlaku dan berlaku secara penuh. Kegagalan salah satu pihak untuk melaksanakan atau memberlakukan hak atau ketentuan dalam Perjanjian ini tidak merupakan pembebasan hak atau ketentuan tersebut. Tidak ada kemitraan, usaha patungan, atau hubungan keagenan yang dimaksudkan atau dibuat oleh Perjanjian ini. Dalam hal penugasan, Persetujuan ini akan mengikat dan menjamin keuntungan para pihak, penerus masing-masing dan pengalihan yang diijinkan. Semua ketentuan dalam Perjanjian ini mengenai pernyataan jaminan, ganti rugi, batasan kewajiban, dan kewajiban pembayaran atas biaya yang terjadi akan tetap berlaku sebelum tanggal penghentian perjanjian berakhir .</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>

			<li><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Pribadi.</p><p>Informasi yang diberikan dalam Perjanjian Pelelangan atau berdasarkan Persyaratan ini akan disimpan oleh IBID sesuai dengan Pernyataan Privasi IBID yang diberikan di www.ibid.astra.co.id</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p></li>
		</ol>
	</div>
</div>